"""Added Surfing Condtion Preferences to User table

Revision ID: c4608160f4bb
Revises: 
Create Date: 2023-09-06 18:36:27.090257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4608160f4bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_wave_height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_wave_height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_wind_mph', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('min_water_temp', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('min_water_temp')
        batch_op.drop_column('max_wind_mph')
        batch_op.drop_column('max_wave_height')
        batch_op.drop_column('min_wave_height')

    # ### end Alembic commands ###
